name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Start MongoDB health check
        run: sleep 10  # Allow MongoDB to initialize

      - name: Start server
        working-directory: ./backend
        env:
          PORT: 8000
          MONGO_URI: mongodb://localhost:27017/moodjournal
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          nohup node server.js > server.log 2>&1 &
          echo "Server started in background"
          sleep 15  # Allow server to initialize
          cat server.log

      - name: Verify server
        run: |
          curl -f http://localhost:8000/api/moods || (echo "Server check failed"; exit 1)

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash
          keploy --version

      - name: Run Keploy tests
        env:
          KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
          APP: ${{ secrets.KEPLOY_APP_ID }}
          BASE_PATH: http://localhost:8000
        run: |
          keploy test-suite --app="$APP" --base-path="$BASE_PATH" --cloud

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keploy-report
          path: ./backend/keploy
          retention-days: 30
