name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash
          keploy --version

      - name: Run Keploy Test Suite
        working-directory: ./backend
        env:
          PORT: 8000
          MONGO_URI: mongodb://localhost:27017/moodjournal
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
          APP: ${{ secrets.KEPLOY_APP_ID }}
          BASE_PATH: http://localhost:8000
        run: |
          # Start the app with proper logging
          nohup node app.js > server.log 2>&1 &
          SERVER_PID=$!
          echo "Waiting for server to start..."
          sleep 25
          
          # Verify app is running
          if curl -sSf http://localhost:8000/api/moods; then
            echo "✅ Server is running"
            cat server.log
          else
            echo "❌ Server failed to start"
            cat server.log
            exit 1
          fi
          
          # Run Keploy tests
          keploy test-suite --app="$APP" --base-path="$BASE_PATH" --cloud
          
          # Clean up
          kill $SERVER_PID || true

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keploy-report
          path: ./backend/keploy
          retention-days: 30
